spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/AlokSachan/common-config.git"
          default-label: master  #branch name
          timeout: 5            #default time out in ms if unable to connect git
          force-pull: true      # clone repo in local
          clone-on-start: true

  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
    port: 5672
server:
  port: 8071
encrypt:
  key: "F44FF9BF37A1D657F34D41CE6CABC"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true